<a href="https://colab.research.google.com/github/js-god/azc3-py/blob/main/pytorch101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

my_vector = torch.tensor([1,2,3,4,5])
print(my_vector)

my_matrix = torch.tensor([[1,2,3],[4,5,6]])
print(my_matrix)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
my_matrix = torch.tensor([[1, 2], [3, 4]])
print(my_matrix)

tensor([[1, 2],
        [3, 4]])


In [ ]:
element = my_matrix[0, 1]
print(element)

tensor(2)


In [ ]:
added_matrix = my_matrix + 10
print(added_matrix)

multiplied_matrix = my_matrix * 2
print(multiplied_matrix)

tensor([[11, 12],
        [13, 14]])
tensor([[2, 4],
        [6, 8]])


In [ ]:
other_matrix = torch.tensor([[5, 6], [7, 8]])
sum_of_matrices = my_matrix + other_matrix
print(sum_of_matrices)

tensor([[ 6,  8],
        [10, 12]])


In [ ]:
my_info = {
    "name": "Alice",
    "age": 30,
    "city": "New York"
}

print(my_info)
print(my_info["name"])
print(my_info["age"])
print(my_info["city"])





{'name': 'Alice', 'age': 30, 'city': 'New York'}
Alice
30
New York


In [ ]:
my_info["occupation"] = "Software Engineer"
print(my_info)

{'name': 'Alice', 'age': 30, 'city': 'New York', 'occupation': 'Software Engineer'}


In [ ]:
my_info["age"] = 31
print(my_info)

{'name': 'Alice', 'age': 31, 'city': 'New York', 'occupation': 'Software Engineer'}


In [ ]:
greeting = "Hello"
name = "Bob"
full_greeting = greeting + ", " + name + "!"
print(full_greeting)

Hello, Bob!


In [ ]:
message = "This is a message."
length = len(message)
print(length)

18


In [ ]:
word = "Python"
first_letter = word[0]
third_letter = word[2]
print(first_letter)
print(third_letter)

P
t


In [ ]:
text = "Hello World"
uppercase_text = text.upper()
lowercase_text = text.lower()
print(uppercase_text)
print(lowercase_text)

HELLO WORLD
hello world


In [ ]:
messy_text = "   Hello   "
cleaned_text = messy_text.strip()
print(cleaned_text)

Hello


In [ ]:
sentence = "This is a sentence."
words = sentence.split()
print(words)

['This', 'is', 'a', 'sentence.']


In [ ]:
name = input("Please enter your name: ")
print(f"Hello, {name}!")

Please enter your name: phon
Hello, phon!


In [ ]:
age_str = input("Please enter your age: ")
age = int(age_str)  # Convert the input string to an integer
print(f"You will be {age + 1} next year!")

Please enter your age: 40
You will be 41 next year!


In [ ]:
try:
  age_str = input("Please enter your age: ")
  age = int(age_str)
  print(f"You will be {age + 1} next year!")
except ValueError:
  print("Invalid input. Please enter a whole number for your age.")

Please enter your age: hi
Invalid input. Please enter a whole number for your age.


In [ ]:
try:
    file = open("my_file.txt", "r")
    content = file.read()
    print(content)
    file.close()  # It's important to close the file when you're done with it!
except FileNotFoundError:
    print("The file 'my_file.txt' was not found.")

The file 'my_file.txt' was not found.


In [ ]:
import random

random_number = random.randint(1, 10)  # Generates a random integer between 1 and 10 (inclusive)
print(f"Your random number is: {random_number}")

Your random number is: 4


In [ ]:
from datetime import datetime

current_time = datetime.now()
print(f"The current time is: {current_time}")



The current time is: 2025-04-25 05:53:54.421152


In [ ]:
class Dog:
    # This is the constructor - it's called when you create a new Dog object
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    # This is a method - it defines an action the Dog can perform
    def bark(self):
        print("Woof!")

    # Another method
    def describe(self):
        print(f"My name is {self.name} and I am a {self.breed}.")


my_dog = Dog("Buddy", "Golden Retriever")
another_dog = Dog("Lucy", "Poodle")

print(my_dog.name)   # Accessing the 'name' attribute
my_dog.bark()        # Calling the 'bark' method
another_dog.describe() # Calling the 'describe' method

Buddy
Woof!
My name is Lucy and I am a Poodle.


In [ ]:
def linear_search(data_list, target):
    for item in data_list:
        if item == target:
            return True  # Found the target!
    return False  # Target not found after checking all items

numbers = [10, 5, 22, 8, 15]
search_for = 18

if linear_search(numbers, search_for):
    print(f"{search_for} was found in the list.")
else:
    print(f"{search_for} was not found in the list.")

18 was not found in the list.


In [31]:
def binary_search(sorted_list, target):
    low = 0
    high = len(sorted_list) - 1

    while low <= high:
        mid = (low + high) // 2  # Integer division to find the middle index
        guess = sorted_list[mid]

        if guess == target:
            return mid  # Target found at index mid
        elif guess < target:
            low = mid + 1  # Target is in the right half
        else:
            high = mid - 1  # Target is in the left half

    return -1  # Target not found

sorted_numbers = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]
search_for = 230

result = binary_search(sorted_numbers, search_for)

if result != -1:
    print(f"{search_for} was found at index {result}.")
else:
    print(f"{search_for} was not found in the list.")

230 was not found in the list.


In [32]:
def merge_sort(data_list):
    if len(data_list) <= 1:
        return data_list

    mid = len(data_list) // 2
    left_half = data_list[:mid]
    right_half = data_list[mid:]

    left_sorted = merge_sort(left_half)
    right_sorted = merge_sort(right_half)

    return merge(left_sorted, right_sorted)

def merge(left, right):
    merged = []
    left_index = 0
    right_index = 0

    while left_index < len(left) and right_index < len(right):
        if left[left_index] <= right[right_index]:
            merged.append(left[left_index])
            left_index += 1
        else:
            merged.append(right[right_index])
            right_index += 1

    # Add any remaining elements from the left or right sub-list
    merged.extend(left[left_index:])
    merged.extend(right[right_index:])

    return merged

unsorted_numbers = [64, 34, 25, 12, 22, 11, 90]
sorted_numbers = merge_sort(unsorted_numbers.copy())
print(f"Unsorted list: {unsorted_numbers}")
print(f"Sorted list: {sorted_numbers}")

Unsorted list: [64, 34, 25, 12, 22, 11, 90]
Sorted list: [11, 12, 22, 25, 34, 64, 90]


In [33]:
def factorial_recursive(n):
    if n == 0:  # Base case
        return 1
    else:
        return n * factorial_recursive(n - 1)

number = 5
result = factorial_recursive(number)
print(f"The factorial of {number} is {result}")

The factorial of 5 is 120


In [34]:
def fibonacci_recursive(n):
    if n <= 1:  # Base cases for n = 0 and n = 1
        return n
    else:
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)

number = 7
result = fibonacci_recursive(number)
print(f"The {number}-th Fibonacci number is {result}")

The 7-th Fibonacci number is 13


In [35]:
from collections import Counter

my_list = ['a', 'b', 'c', 'a', 'b', 'b', 'a']
item_counts = Counter(my_list)
print(item_counts)
print(item_counts['b'])  # Get the count of 'b'

Counter({'a': 3, 'b': 3, 'c': 1})
3


In [36]:
from collections import deque

my_deque = deque([1, 2, 3])
my_deque.append(4)
my_deque.appendleft(0)
print(my_deque)
my_deque.pop()
my_deque.popleft()
print(my_deque)

deque([0, 1, 2, 3, 4])
deque([1, 2, 3])


In [37]:
import itertools

# Generate combinations of length 2 from a list
my_list = [1, 2, 3]
combinations = list(itertools.combinations(my_list, 2))
print(combinations)

# Generate permutations of a list
permutations = list(itertools.permutations(my_list))
print(permutations)

[(1, 2), (1, 3), (2, 3)]
[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [38]:
import numpy as np

my_array = np.array([64, 34, 25, 12, 22, 11, 90])
sorted_array = np.sort(my_array)
print(f"Sorted NumPy array: {sorted_array}")

Sorted NumPy array: [11 12 22 25 34 64 90]


In [39]:
import torch

float_tensor = torch.tensor([1.0, 2.0, 3.0])
print(float_tensor.dtype)

int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(int_tensor.dtype)

long_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
print(long_tensor.dtype)

bool_tensor = torch.tensor([True, False, True])
print(bool_tensor.dtype)

torch.float32
torch.int32
torch.int64
torch.bool


In [40]:
zeros_tensor = torch.zeros(2, 3)  # Creates a 2x3 tensor filled with zeros
print(zeros_tensor)

ones_tensor = torch.ones(4)      # Creates a 1D tensor (vector) of size 4 filled with ones
print(ones_tensor)

rand_tensor = torch.rand(2, 2)   # Creates a 2x2 tensor with random values between 0 and 1
print(rand_tensor)

randn_tensor = torch.randn(3, 3)  # Creates a 3x3 tensor with random values from a standard normal distribution
print(randn_tensor)

arange_tensor = torch.arange(0, 10, 2) # Creates a 1D tensor with values from 0 to 10 (exclusive) with a step of 2
print(arange_tensor)

linspace_tensor = torch.linspace(0, 1, 5) # Creates a 1D tensor with 5 evenly spaced values from 0 to 1 (inclusive)
print(linspace_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1., 1., 1., 1.])
tensor([[0.0917, 0.5088],
        [0.6072, 0.8235]])
tensor([[-0.5756, -1.1505,  0.6886],
        [-0.7534,  1.3786, -0.4446],
        [ 0.3229,  0.7605, -1.0019]])
tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [41]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

sum_tensor = torch.add(a, b)
print(f"Sum:\n{sum_tensor}")

product_tensor = torch.matmul(a, b)
print(f"Product:\n{product_tensor}")

mean_value = torch.mean(a.float()) # Need to convert to float for mean calculation
print(f"Mean of a: {mean_value}")

Sum:
tensor([[ 6,  8],
        [10, 12]])
Product:
tensor([[19, 22],
        [43, 50]])
Mean of a: 2.5


In [42]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    gpu_tensor = a.to(device)
    print(f"Tensor on GPU:\n{gpu_tensor}")
else:
    print("CUDA is not available, using CPU.")

CUDA is not available, using CPU.
